---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cosmic-atomic
# description will be included in the image's metadata
description: Cosmic Atomic with a bluefin touch

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-cosmic
image-version: 43

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: os-release
    properties:
      NAME: Cosmic Atomic
      PRETTY_NAME: Fedora Cosmic Atomic
  # copied from bluebuild base-image repository ^^
  - type: dnf
    repos:
      copr:
        - rowanfr/fw-ectool
    install:
      packages:
        - fw-ectool
        - python3-pip
        - tailscale
        - waydroid
        - android-tools
        - containerd
        - docker-cli
        - docker-buildx
        - docker-compose
        - rocm-smi
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
    group-install:
      with-optional: true
      packages:
        - virtualization
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
  - type: default-flatpaks
    configurations:
      - scope: system  
      - notify: true
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
        install:
          - net.nokyan.Resources # this Flatpak is appended to the install list
          - app.zen_browser.zen # this one too
          - io.anytype.anytype # this one too
          - com.spotify.Client # gotta somehow figure out spicetify
          - io.github.celluloid_player.Celluloid # look videos!!
          - io.github.shiftey.Desktop
          - com.vscodium.codium
          - io.bassi.Amberol
          - me.iepure.devtoolbox
          - org.gnome.DejaDup
          - org.gnome.gitlab.somas.Apostrophe
          - org.gnome.TextEditor
          - com.nextcloud.desktopclient.nextcloud
  - type: default-flatpaks
    configurations:
      - scope: system
      - notify: true
        repo:
          url: https://apt.pop-os.org/cosmic/cosmic.flatpakrepo
          name: cosmic
          title: "Cosmic flatpak repo"
  - type: systemd
    system:  
      enabled:
        - podman.socket
        - tailscaled.service
        - libvirtd.service
  - type: files
    files:
#      - source: bluefin/system_files/shared/usr/bin 
#        destination: /usr/bin
#      - source: bluefin/system_files/shared/usr/libexec
#        destination: /usr/libexec
#      - source: bluefin/system_files/shared/usr/lib/tmpfiles.d
#        destination: /usr/lib/tmpfiles.d
#      - source: bluefin/system_files/shared/usr/share/ublue-os/bluefin-cli
#        destination: /usr/share/ublue-os/bluefin-cli
#      - source: bluefin/system_files/shared/usr/share/ublue-os/homebrew
#        destination: /usr/share/ublue-os/homebrew
#      - source: bluefin/system_files/shared/usr/share/ublue-os/quadlets
#        destination: /usr/share/ublue-os/quadlets
      # Avoid Bluefin branding
      # - source: bluefin/system_files/silverblue/usr/share:
       # destination: /usr/share
#      - source: bluefin/system_files/dx
#        destination: /
      - source: system/
        destination: /
  - type: justfiles
    validate: false
    include:
      - bluefin-apps.just
      - bluefin-system.just
      - bluefin-tools.just
  - type: signing
