---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cosmic-atomic
# description will be included in the image's metadata
description: Cosmic Atomic with a bluefin touch

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 43

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: base/common.yml
  - type: os-release
    properties:
      NAME: Cosmic Atomic
      PRETTY_NAME: Fedora Cosmic Atomic (FROM Fedora cosmic-atomic)
  - from-file: base/post-build.yml
  # copied from bluebuild base-image repository ^^
  - type: dnf
    repos:
      copr:
        - rowanfr/fw-ectool
    install:
      packages:
        - fw-ectool
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
    group-install:
      with-optional: true
      packages:
        - virtualization
  - type: default-flatpaks
    configurations:
      - scope: system  
      - notify: true
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
        install:
          - net.nokyan.Resources # this Flatpak is appended to the install list
          - app.zen_browser.zen # this one too
          - io.anytype.anytype # this one too
          - com.spotify.Client # gotta somehow figure out spicetify
          - io.github.celluloid_player.Celluloid # look videos!!
          - com.unicornsonlsd.finamp
          - io.github.shiftey.Desktop
          - com.vscodium.codium
          - io.bassi.Amberol
          - me.iepure.devtoolbox
          - org.gnome.DejaDup
          - org.gnome.gitlab.somas.Apostrophe
          - org.gnome.TextEditor
          - com.nextcloud.desktopclient.nextcloud
  - type: systemd
    system:  
      enabled:
        - podman.socket
        - tailscaled.service
        - libvirtd.service
